### ISSUE TITLE
Series Name and Index

### ISSUE THREAD

**Issue by teamcoltra** [e-e-e/open-packaging-format#1]
"meta":[{"$":{"content":"1","name":"calibre:series_index"}},{"$":{"content":"Wild Dreams","name":"calibre:title_sort"}},{"$":{"content":"10.00","name":"calibre:rating"}},{"$":{"content":"2014-10-01T10:35:19.955000+00:00","name":"calibre:timestamp"}}

I realize these are calibre specific but they are basically standard parts of ebooks now... I tried to add it myself but I cannot figure out how to grab them properly.

**Comment by e-e-e** [comment]
Could you provide me more detail about exactly what you are having trouble with?
Also what is the original xml data that you are parsing?

**Comment by teamcoltra** [comment]
Specifically series_index and series name... but perhaps all the standard calibre metadata such as calibre:rating as well. 
```
<?xml version='1.0' encoding='utf-8'?>
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="uuid_id">
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlnspf="http://www.idpf.org/2007/opf">
<dc:identifier opf:scheme="calibre" id="calibre_id">58</dc:identifier>
<dc:identifier opf:scheme="uuid" id="uuid_id">fabc6e5f-dba8-471d-b4f3-595101d2a608</dc:identifier>
<dc:title>Foundation</dc:title>
<dc:creator opf:file-as="Asimov, Isaac" opf:role="aut">Isaac Asimov</dc:creator>
<dc:contributor opf:file-as="calibre" opf:role="bkp">calibre (1.2.0) [http://calibre-ebook.com]</dc:contributor>
<dc:date>1951-01-02T05:00:00+00:00</dc:date>
<dc:description>DESCRIPTION</dc:description>
<dc:publisher>Spectra</dc:publisher>
<dc:identifier opf:scheme="AMAZON">0553382578</dc:identifier>
<dc:identifier opf:scheme="GOOGLE">IwywDY4P6gsC</dc:identifier>
<dc:identifier opf:scheme="ISBN">9780553293357</dc:identifier>
<dc:language>eng</dc:language>
<meta content="{&quot;Isaac Asimov&quot;: &quot;&quot;}" name="calibre:author_link_map"/>
<meta content="Foundation" name="calibre:series"/>
<meta content="3" name="calibre:series_index"/>
<meta content="8.0" name="calibre:rating"/>
<meta content="0101-01-01T05:00:00+00:00" name="calibre:timestamp"/>
<meta content="Foundation" name="calibre:title_sort"/>
</metadata>
<guide>
<reference href="Foundation - Isaac Asimov.jpg" title="Cover" type="cover"/>
</guide>
</package>
```

In particular:

```
<meta content="{&quot;Isaac Asimov&quot;: &quot;&quot;}" name="calibre:author_link_map"/>
<meta content="Foundation" name="calibre:series"/>
<meta content="3" name="calibre:series_index"/>
<meta content="8.0" name="calibre:rating"/>
<meta content="0101-01-01T05:00:00+00:00" name="calibre:timestamp"/>
<meta content="Foundation" name="calibre:title_sort"/>
```

**Comment by e-e-e** [comment]
Cool. I get you!

I will be adding and refining this module over the next month as part of the project I am using it for an will look at adding a simple why of getting namespaced values generally - so that this data can be exposed simply. It might take me a while to get to it - as I am working on other work at the moment - but will let you know when its available.

**Comment by e-e-e** [comment]
Hey @teamcoltra, I started looking at adding this today.
I am thinking it will be exposed by an interface like this:
```js
opf.meta.calibre.titleSort
opf.meta.calibre.timestamp
opf.meta.calibre.series
```
where they’re get/set attributes that accept/return either an array of values or a singular value.
although perhaps just a value - i need to do a bit of research to see if content/name pairs can be duplicates. Perhaps the array in that case is uneccessary.

**Comment by e-e-e** [comment]
@teamcoltra you can now read and write meta tags. 
The relevant commits are - 566bbecaf785875ffe98cc3b57a5eaa48afee320 and 728a4a1f061aaddd43e958318940cbda08e7db61.
Let me know if you experience any issues. For now I will close this issue.

**Comment by teamcoltra** [comment]
Hey, I know this is closed but just wanted to let you know that I wrote a thank you comment when I saw this stuff way back in September but stumbled accross this again and must have not submitted it so I just wanted to say that worked perfectly and thank you :)
